spring:
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

server:
  port: 8080
